name: Reusable Build & Push

on:
  workflow_call:
    inputs:
      subdir:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SUBDIR: ${{ inputs.subdir }}

    defaults:
      run:
        working-directory: ${{ env.SUBDIR }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Validate
        run: mvn -DskipTests=true -q clean verify

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push via root Makefile
        env:
          REGISTRY: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: ${{ github.event.repository.name }}-${{ env.SUBDIR }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          make -C .. docker-build-push-dev \
            SUBDIR="${SUBDIR}" \
            BUILD_CONTEXT="${SUBDIR}" \
            DOCKERFILE="${SUBDIR}/Dockerfile" \
            REGISTRY="${REGISTRY}" \
            REPOSITORY="${REPOSITORY}" \
            IMAGE_TAG="${IMAGE_TAG}"
