name: Build and Test Maven Project with Docker to DockerHub

on:
  push:
    branches: [develop]
    paths:
      - "simple-crud-logging-gateway/**"

  pull_request:
    branches: [develop] # base branch of the PR
    paths:
      - "simple-crud-logging-gateway/**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: simple-crud-logging-gateway

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK (for Maven)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Step 3: Install Maven
      - name: Set up Maven
        run: |
          sudo apt-get install -y maven

      # Step 4: Cache Maven dependencies (optional but helps with faster builds)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Validate the Maven project (check for any errors)
      - name: Validate Maven Project
        run: mvn clean verify -DskipTests=true

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build, tag, and push Docker image using Makefile
      - name: Build and push Docker image using Makefile
        env:
          REGISTRY: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: ${{ github.event.repository.name }}-simple-crud-logging-gateway
          IMAGE_TAG: ${{ github.sha }}
        run: make docker-build-push-dev
